# Generated by Django 2.1.5 on 2019-01-08 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_auto_20190107_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('url_upload', models.TextField()),
            ],
        ),
    ]
