# Generated by Django 2.1.5 on 2019-01-08 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_word'),
        ('uploads', '0003_urlupload'),
    ]

    operations = [
    ]
