# Generated by Django 2.1.4 on 2019-01-08 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='NGram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(unique=True)),
                ('n_gram', models.TextField()),
                ('count', models.IntegerField()),
                ('frequency', models.FloatField(null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='ngram',
            unique_together={('token', 'n_gram')},
        ),
    ]
